random_seed: 0
save_fig: True
output_path: 'results'
device: 'auto'
mode: 'benchmark' # 'benchmark' or 'debug'
force_rerun: True

realistic_synthetic_mode: null
alpha: 5
percentage: 0.1
run_id: "adbench_synthetic_anomaly"


defaults:
  - _self_
  - dataset: A_synthetic_f4_s5000_c2_r0.025_0.025_seed_0
  - model: 'DTECategorical'
  - training_method: 'iterative_dataset_sampling'
  - override hydra/launcher: 'joblib'


hydra:
  launcher:
      n_jobs: 2
  sweeper: 
    params:
      # All datasets that start with A_synthetic
      dataset:  glob(ADBench_synthetic*)
      training_method: unsupervised, iterative_dataset_sampling
