random_seed: 0
save_fig: True
output_path: 'dataset'
device: 'auto'
mode: 'benchmark' # 'benchmark' or 'debug'


realistic_synthetic_mode: ["global", "additive_noise", "multiplicative_noise", "local"]
alpha: 5
percentage: 0.1
run_id: "datagen"


defaults:
  - _self_
  - dataset: wine
  - override hydra/launcher: 'joblib'


hydra:
  launcher:
    n_jobs: 4
  sweeper: 
    params:
      dataset: glob(*, *synthetic*)
