random_seed: 0
save_fig: True
output_path: 'results'
device: 'auto'
mode: 'benchmark' # 'benchmark' or 'debug'
force_rerun: True

# realistic_synthetic_mode: ["global", "additive_noise", "multiplicative_noise", "local"]
realistic_synthetic_mode: null
alpha: 5
percentage: 0.1
run_id: "pushing_iteration"


defaults:
  - _self_
  - dataset: WBC
  - model: 'DTECategorical'
  - training_method: 'unsupervised'
  - override hydra/launcher: 'joblib'


hydra:
  launcher:
      n_jobs: 2
  sweeper: 
    params:
      random_seed: 0,1,2
      # All datasets that start with A_synthetic
      # dataset: ADBench_synthetic_39_vertebral, ADBench_synthetic_44_Wilt, ADBench_synthetic_42_WBC, ADBench_synthetic_27_PageBlocks, ADBench_synthetic_19_landsat, ADBench_synthetic_5_campaign
      dataset: CIFAR10, FashionMNIST, MVTec-AD, SVHN
      training_method: unsupervised, iterative_dataset_sampling
