random_seed: 0
save_fig: True
output_path: 'results'
device: 'auto'
mode: 'benchmark' # 'benchmark' or 'debug'


realistic_synthetic_mode: null
alpha: 5
percentage: 0.1
run_id: "all_db_all_training"


defaults:
  - _self_
  - dataset: A_synthetic_f10_s5000_c4_r0.033_0.033_0.033_seed_0
  - model: 'DTECategorical'
  - training_method: 'unsupervised'
  - override hydra/launcher: 'joblib'


hydra:
  launcher:
      n_jobs: 2
  sweeper: 
    params:
      # All datasets that start with A_synthetic
      dataset:  glob(A_synthetic_f*)
      training_method: unsupervised, iterative_dataset_sampling
