random_seed: 0
save_fig: True
output_path: 'results'
device: 'auto'
mode: 'benchmark' # 'benchmark' or 'debug'


realistic_synthetic_mode: null
alpha: 5
percentage: 0.1
run_id: "grid_search"


defaults:
  - _self_
  - dataset: synthetic_f1000_s5000_c40_r0.01_0.01_0.01_0.01_0.01_v0
  - model: 'DTECategorical'
  - training_method: 'unsupervised'
  - override hydra/launcher: 'joblib'


hydra:
  launcher:
      n_jobs: 1
  sweeper: 
    params:
      dataset: synthetic_f1000_s5000_c40_r0.01_0.01_0.01_0.01_0.01_v0
      training_method: unsupervised
