random_seed: 0
save_fig: True
output_path: 'results'
device: 'auto'
mode: 'benchmark' # 'benchmark' or 'debug'
force_rerun: True

realistic_synthetic_mode: ["global", "additive_noise", "multiplicative_noise", "local"]
alpha: 5
percentage: 0.1
run_id: "adbench_synthetic_anomaly"


defaults:
  - _self_
  - dataset: WBC
  - model: 'DTECategorical'
  - training_method: 'unsupervised'
  - override hydra/launcher: 'joblib'


hydra:
  launcher:
      n_jobs: 2
  sweeper: 
    params:
      # All datasets that start with A_synthetic
      dataset:  glob(*,A_synthetic_f*)
      training_method: unsupervised, iterative_dataset_sampling
